create table covid_history_global
(
        id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
        DATE_INFO       DATE,
        DATETIME_INFO   TIMESTAMP(6),
        NEW_CASES       FLOAT,
        ACTIVE_CASES    FLOAT,
        CRITICAL_CASES  FLOAT,
        RECOVERED_CASES FLOAT,
        TOTAL_CASES     FLOAT,
        NEW_DEATHS      FLOAT,
        TOTAL_DEATHS    FLOAT,
        TOTAL_TESTS     FLOAT
)